version: '3.1'
services:
  auth_app:
    build: ./services/auth
    command: npm run dev
    volumes:
      - ./services/auth:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      APP_PORT: 8000
      DB_URL: mongodb://db:27017/auth
      USERS_URL: http://users_app:8000
      ACCESS_TOKEN_SECRET: e8f22ec6850ef9a76f2d63cd8053d7934d9025204d526e01726eef7d097770f900dce6d17d7448611227a1c2b48873e7f6b59a663621de781d8898a59611b567
      REFRESH_TOKEN_SECRET: 18ac72eb80d33312f899c4c35cf55c7f72cf2a9f6c6de1cd6fbd1123533107ba8073af65658934e7e6efe8e578d631f1470be3ed3b80ebce9e10da32bec84c02

  users_app:
    build: ./services/users
    command: npm run dev
    volumes:
      - ./services/users:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8002:8000"
    depends_on:
      - db
    environment:
      APP_PORT: 8000
      DB_URL: mongodb://db:27017/users
      AUTH_URL: http://auth_app:8000

  products_app:
    build: ./services/products
    command: npm run dev
    volumes:
      - ./services/products:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8003:8000"
    depends_on:
      - db
    environment:
      APP_PORT: 8000
      DB_URL: mongodb://db:27017/products
      AUTH_URL: http://auth_app:8000

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017