version: '3.1'
services:
  auth_app:
    build: ./services/auth
    command: npm run dev
    volumes:
      - ./services/auth:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      APP_PORT: 8080
      DB_URL: mongodb://db:27017/auth
      USERS_URL: http://users_app:8080
      ACCESS_TOKEN_SECRET: it-should-be-base64-access
      REFRESH_TOKEN_SECRET: it-should-be-base64-refresh

  users_app:
    build: ./services/users
    command: npm run dev
    volumes:
      - ./services/users:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8082:8080"
    depends_on:
      - db
    environment:
      APP_PORT: 8080
      DB_URL: mongodb://db:27017/users
      AUTH_URL: http://auth_app:8080

  products_app:
    build: ./services/products
    command: npm run dev
    volumes:
      - ./services/products:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8083:8080"
    depends_on:
      - db
    environment:
      APP_PORT: 8080
      DB_URL: mongodb://db:27017/products
      AUTH_URL: http://auth_app:8080

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  docs:
    build: ./services/docs
    command: npm run dev
    volumes:
      - ./services/docs:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8084:8080"
    environment:
      APP_PORT: 8080