version: '3.1'
services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mongodb://db:27017/catalog
  db:
    image: db
    restart: always
    ports:
      - 27017:27017
